CFLAGS = -O2 -Wall -Wextra -pedantic -std=c++14 -IC:/msys64/mingw64/include -LC:/msys64/mingw64/lib
CXX = g++


SRC = quote_tests.cpp quote.cpp
BINS = quote_tests.exe
OBJ = 
DEPS = quote.h


all: $(BINS)


quote_tests.exe: $(SRC) $(DEPS)
	$(CXX) -o $@ $^ $(CFLAGS)


clean:
	rm -f $(BINS) $(OBJ)


.PHONY: all, clean
